# This is a basic workflow
name: Github Pages Build and Deploy

# Controls when the action will run. Triggers the workflow on push request
# events on the main branch
on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.1

      - name: Install and Build
        run: |
          mkdir -p dist
          cp -r src/* dist

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.0.0
        with:
          BRANCH: gh-pages
          FOLDER: dist
